"""create tables for pedidos #27

Revision ID: 95354a0cc046
Revises:
Create Date: 2026-10-04 19:38:03.783965

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95354a0cc046"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clientes",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
        ),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("telefono", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("direccion", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clientes")),
        sa.UniqueConstraint("email", name=op.f("uq_clientes_email")),
    )
    op.create_table(
        "productos",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
        ),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("tipo", sa.String(length=30), nullable=False),
        sa.Column("caracteristicas", sa.String(length=150), nullable=True),
        sa.Column("espesor_mm", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "tipo IN ('vidrio','aluminio','otro')",
            name=op.f("ck_productos_tipo_valido"),
        ),
        sa.CheckConstraint("espesor_mm > 0", name=op.f("ck_productos_espesor_positivo")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_productos")),
    )
    op.create_index("idx_productos_tipo", "productos", ["tipo"], unique=False)
    op.create_table(
        "pedidos",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
        ),
        sa.Column("cliente_id", sa.Uuid(), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("fecha_entrega", sa.Date(), nullable=True),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estado IN ('pendiente','en_proceso','completado','cancelado')",
            name=op.f("ck_pedidos_estado_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clientes.id"],
            name=op.f("fk_pedidos_cliente_id_clientes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pedidos")),
    )
    op.create_index("idx_pedidos_cliente_id", "pedidos", ["cliente_id"], unique=False)
    op.create_index("idx_pedidos_estado", "pedidos", ["estado"], unique=False)
    op.create_table(
        "piezas",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
        ),
        sa.Column("pedido_id", sa.Uuid(), nullable=False),
        sa.Column("producto_id", sa.Uuid(), nullable=False),
        sa.Column("ancho_mm", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("largo_mm", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("operario_asignado", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estado IN ('pendiente','en_corte','completado')",
            name=op.f("ck_piezas_estado_valido"),
        ),
        sa.CheckConstraint("ancho_mm > 0", name=op.f("ck_piezas_ancho_positivo")),
        sa.CheckConstraint("cantidad > 0", name=op.f("ck_piezas_cantidad_positiva")),
        sa.CheckConstraint("largo_mm > 0", name=op.f("ck_piezas_largo_positivo")),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedidos.id"],
            name=op.f("fk_piezas_pedido_id_pedidos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
            name=op.f("fk_piezas_producto_id_productos"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_piezas")),
    )
    op.create_index("idx_piezas_estado", "piezas", ["estado"], unique=False)
    op.create_index("idx_piezas_operario", "piezas", ["operario_asignado"], unique=False)
    op.create_index("idx_piezas_pedido_id", "piezas", ["pedido_id"], unique=False)
    op.create_index("idx_piezas_producto_id", "piezas", ["producto_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_piezas_producto_id", table_name="piezas")
    op.drop_index("idx_piezas_pedido_id", table_name="piezas")
    op.drop_index("idx_piezas_operario", table_name="piezas")
    op.drop_index("idx_piezas_estado", table_name="piezas")
    op.drop_table("piezas")
    op.drop_index("idx_pedidos_estado", table_name="pedidos")
    op.drop_index("idx_pedidos_cliente_id", table_name="pedidos")
    op.drop_table("pedidos")
    op.drop_index("idx_productos_tipo", table_name="productos")
    op.drop_table("productos")
    op.drop_table("clientes")
    # ### end Alembic commands ###
